name: Remote SSH repo update and restart service
on:
  push:
      branches:
        - master
jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v1.0.3
      env: 
        WORK_DIR: ${{ secrets.WORK_DIR }}
        SERVICE: ${{ secrets.SSH_SERVICE }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_UBUNTU_KEY }}
        port: ${{ secrets.SSH_PORT }}
        envs: WORK_DIR,SERVICE
        script: |
          cd $WORK_DIR
          git pull
          npm ci
          pm2 restart $SERVICE
